* This Course (Course 1 in Web Design Specialization)
Covered in this course:

- HTML syntax and semantics

- Accessibility

- How to start coding

** Week 1 - questions

what happens when you type in a URL?

what tools do you need in order to code?

what is HTML? HTML5?

** Week 2 - some theory, some code

DOM

standard HTML tags

** Week 3 - putting it all together

Validating code

- syntax

- accessibility

Domain name registration and web hosting

Final project that

- has several pages

- passes W3C validation

- passes WAVE accessibility review



** Course content
weekly videos

- lecture format - watch anywhere

- demo format - type along with the video

weekly readings

- free online textbook: [[http://textbooks.opensuny.org/the-missing-link-an-introduction-to-web-development-and-programming]]

- free online articles

weekly assessments

- quizzes

final project

- straightforward, but the final result will be ugly (CSS comes next!)


** Advice on completing this course

- work with peers

- ask questions

- never spend more than 20 minutes at a time on a problem. Don't be afraid to walk away and think about the task, or ask someone for advice.

- learn how to look things up. Independent research and learning is key in all fields, but especially so when working with computers. This is the single most important skill separating computer illiterates and computer masters.

- practice. You will not learn the material if you do not use the material. The best learning comes from making mistakes, and figuring out what you did wrong. Don't be afraid of screwing up, as screwing up is the fastest way to learn.


* Useful tools
** Firefox with Tilt 3D
https://addons.mozilla.com/en-US/firefox/addon/tilt


* What is HTML5
Hypertext Markup Language, version 5. Markup languages annotate documents, they are not programming languages. In HTML, we use tags to indicate things like headings, lists, links, images, text, etc.

** `.html` files
`.html` is the file extension for HTML files. By convention, your computer knows that `.html` files should be opened in the browser. Your browser knows how to make sense of the file, and properly display its contents.

We can write `.html` files by hand, because `.html` files are just text with some special formatting and syntax. It's very easy to read, and you can make sense out of it even if you don't know what the tags mean.

** Example HTML document
[[./week-1-docs/example_1.html]]

note that this is mostly English. The tags help the computer know what to do with the English.

The structure of the tags is called the syntax of HTML. Tags need to be opened and closed. Note the syntax for opening a tag (look at the beginning of the lines) and the syntax for closing a tag (at the end of the lines).

Each tag has a purpose, and most of them have sensible names (some of them don't, we'll make note of them). The meaning of the tags is called the semantics of HTML. Most tags are almost human readable. `<h1>hello world</h1>` means we are dealing with a "header" whose text is "hello world".




* History of HTML
** HTML version 1
Developed in 1990 as a way to link documents electronically. The internet as we know it didn't really exist back then, and this first version of HTML was used primarily by scientists who didn't care about color or styling. They just wanted to be able to send structured documents to their peers on the other side of the country (eventually, world). More on the history of networks, and the Internet, can be found in the textbook reading (which isn't too bad).

By 1993, the internet had started developing, and the users wanted graphics and colors. The Mosaic browser was developed, and it was the first graphical browser. Mosaic launched what we would recognize as the early form of the modern internet, and cat pictures spread everywhere. Mosaic caused a 341,364% annual growth of internet users, and gained competitors (Netscape in 1994, Internet Explorer in 1995).

** Browser Wars
Every browser tried to stand out as better than the other browser, so they started implementing proprietary tags like `<marquee>` and `<blink>` that wouldn't work in competitor browsers.

Computer people people got upset, and started trying to standardize HTML. Groups like IETF, W3C and WAI formed with the goal of deciding what is and is not valid HTML.

Changes in standards

| year        | movement                                      |
|-------------+-----------------------------------------------|
| 1990 - 1994 | HTML was text based, with no fancy stuff      |
| 1993        | Mosaic brings images into play                |
| 1995 - 1999 | Browser compatibility is gone                 |
| 2000 - 2005 | Browsers agree to separate content from style |
| 2005 - 2008 | HTML with CSS becomes the standard            | 

HTML verisons

| year | version   |                                          |
|------+-----------+------------------------------------------|
| 1993 | HTML 1.0  | Tim Berners-Lee                          |
| 1995 | HTML 2.0  | (Internet Engineering Task Force (IETF)) |
| 1996 | CSS 1     |                                          |
| 1997 | HTML 3.2  | (W3C), included proprietary stuff        |
| 1997 | HTML 4.0  | tried to normalize features              |
| 1998 | CSS 2     |                                          |
| 1999 | HTML 4.01 | Multiple document types                  |
| 2012 | HTML 5    | Standardization (at long last)           |

Nowadays, HTML5 is the One True Standard for HTML documents. All modern web tech is now based on HTML, CSS, JavaScript, and the DOM.
  

* How does the Internet work

